services:
  frontend:
    build:
      context: ..
      dockerfile: infra/frontend.Dockerfile
    container_name: expophoenixworld-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/expophoenix.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/expophoenix.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
